"""Filesystem-backed Agenda storage facade.

Stage 3 starts with a single visible storage boundary for Agenda so narrower
task, DAG, and log storage modules can grow behind this facade later without
changing the package import surface. Canonical path ownership and task schema
primitives live in focused sibling modules and are re-exported here where
useful.
"""

from azq.agenda.task_storage import (
    CanonicalDeliverableValidationError,
    load_all_tasks,
    load_deliverable_tasks,
    load_task,
    load_tasks_for_deliverable,
    next_task_id,
    parse_task_markdown,
    parse_task_record,
    save_task,
    serialize_task_markdown,
    serialize_task_record,
    task_from_markdown,
    task_to_markdown,
    validate_canonical_deliverable,
    validate_parent_deliverable,
    write_task,
)
from azq.agenda.paths import (
    AGENDA_DIR,
    DAGS_DIR,
    DAG_FILE_PREFIX,
    DAG_FILE_SUFFIX,
    DATA_DIR,
    LOGS_DIR,
    TASKS_DIR,
    TASK_FILE_PREFIX,
    TASK_FILE_GLOB,
    TASK_FILE_SUFFIX,
    TASK_LOG_FILE_SUFFIX,
    dag_file_path,
    ensure_agenda_dirs,
    ensure_dags_dir,
    ensure_logs_dir,
    ensure_tasks_dir,
    list_task_files,
    task_file_path,
    task_log_file_path,
)
from azq.agenda.schemas import (
    DEPENDENCIES_HEADING,
    DESCRIPTION_HEADING,
    EXECUTION_NOTES_HEADING,
    GRAPH_ID_SUFFIX,
    TASK_ID_PATTERN,
    TASK_INTENT_HEADING,
    normalize_dag_record,
    normalize_task_record,
    task_id_number,
)


__all__ = [
    "DATA_DIR",
    "AGENDA_DIR",
    "TASKS_DIR",
    "DAGS_DIR",
    "LOGS_DIR",
    "TASK_FILE_PREFIX",
    "TASK_FILE_SUFFIX",
    "TASK_FILE_GLOB",
    "DAG_FILE_PREFIX",
    "DAG_FILE_SUFFIX",
    "TASK_LOG_FILE_SUFFIX",
    "TASK_ID_PATTERN",
    "GRAPH_ID_SUFFIX",
    "TASK_INTENT_HEADING",
    "DEPENDENCIES_HEADING",
    "DESCRIPTION_HEADING",
    "EXECUTION_NOTES_HEADING",
    "CanonicalDeliverableValidationError",
    "ensure_agenda_dirs",
    "ensure_tasks_dir",
    "ensure_dags_dir",
    "ensure_logs_dir",
    "task_file_path",
    "dag_file_path",
    "task_log_file_path",
    "list_task_files",
    "task_id_number",
    "normalize_task_record",
    "normalize_dag_record",
    "serialize_task_record",
    "serialize_task_markdown",
    "task_to_markdown",
    "parse_task_record",
    "parse_task_markdown",
    "task_from_markdown",
    "validate_canonical_deliverable",
    "validate_parent_deliverable",
    "load_task",
    "load_all_tasks",
    "load_tasks_for_deliverable",
    "load_deliverable_tasks",
    "next_task_id",
    "write_task",
    "save_task",
]
